export const STATIONS = [
  {
    id: 'welcome',
    num: '01',
    kicker: 'Hero',
    title: 'Sua operação inteira. Em um só lugar.',
    lead: 'Planeje, organize e acompanhe o dia da sua operação com mais leveza, eficiência e controle.',
    points: [],
    stories: [] as { label: string; hint: string; tone: 'rose' | 'purple' | 'orange' }[],
    stats: [] as { label: string; hint: string }[],
    side: 'left' as const,
  },
  {
    id: 'chaos',
    num: '02',
    kicker: 'Fragmentação',
    title: 'Um dia cheio. Em muitos lugares.',
    lead: 'Agenda, tarefas, e-mails, documentos e WhatsApp se desmontam no ar.',
    points: ['Agenda', 'Tarefas', 'WhatsApp'],
    stories: [],
    stats: [],
    side: 'left' as const,
  },
  {
    id: 'center',
    num: '03',
    kicker: 'Virada',
    title: 'Tudo muda de direção.',
    lead: 'As linhas caóticas se organizam. As peças passam por você e convergem no M.',
    points: [],
    stories: [],
    stats: [],
    side: 'right' as const,
  },
  {
    id: 'day',
    num: '04',
    kicker: 'Portal',
    title: 'Seu dia começa aqui.',
    lead: 'O M abre como portal. Você atravessa o logo e, do outro lado, está a MONA.',
    points: [],
    stories: [],
    stats: [],
    side: 'left' as const,
  },
  {
    id: 'clients',
    num: '05',
    kicker: 'Passeio',
    title: 'Visitar o software.',
    lead: 'A câmera não desce a página: entra em tarefas, agenda e financeiro.',
    points: [],
    stories: [
      { label: 'Tarefas do dia', hint: 'Veja o que precisa ser feito agora.', tone: 'rose' as const },
      { label: 'Agenda', hint: 'Seus compromissos de hoje.', tone: 'purple' as const },
      { label: 'Financeiro', hint: 'Acompanhe seus resultados.', tone: 'orange' as const },
    ],
    stats: [],
    side: 'left' as const,
  },
  {
    id: 'flow',
    num: '06',
    kicker: 'Cliente',
    title: 'Cada cliente no seu lugar.',
    lead: 'O card cresce até virar a operação. Informações, tarefas, arquivos e mais em camadas, no lugar certo.',
    points: ['Visão', 'Tarefas', 'Arquivos'],
    stories: [],
    stats: [],
    side: 'left' as const,
  },
  {
    id: 'tools',
    num: '07',
    kicker: 'Processo',
    title: 'Do primeiro contato ao resultado.',
    lead: 'As camadas se alinham e viram caminho. A MONA como sistema da operação.',
    points: ['Onboarding', 'Execução', 'Resultado'],
    stories: [],
    stats: [],
    side: 'right' as const,
  },
  {
    id: 'shift',
    num: '08',
    kicker: 'Transformação',
    title: 'O antes vira depois.',
    lead: 'Uma linha atravessa o caos. Tudo que ela toca entra na MONA.',
    points: [],
    stories: [],
    stats: [],
    side: 'left' as const,
  },
  {
    id: 'grow',
    num: '09',
    kicker: 'Arquitetura',
    title: 'A MONA cria estrutura.',
    lead: 'Clientes, integrações e processos orbitam o núcleo. Quanto mais cresce, mais estrutura.',
    points: ['Clientes', 'Integrações', 'Processos'],
    stories: [],
    stats: [],
    side: 'right' as const,
  },
  {
    id: 'cta',
    num: '10',
    kicker: 'Simplicidade',
    title: 'Organize o hoje. Impulsione o amanhã.',
    lead: 'Tudo converge de novo em um único M. A história continua quando você entra.',
    points: [],
    stories: [],
    stats: [
      { label: 'Mais tempo', hint: '⚡' },
      { label: 'Mais clientes', hint: '✦' },
      { label: 'Mais resultado', hint: '📈' },
    ],
    side: 'left' as const,
  },
] as const
