export const Permissions = {
  Dashboard: 'Dashboard',
  ClientsRead: 'Clients.Read',
  ClientsWrite: 'Clients.Write',
  EmployeesRead: 'Employees.Read',
  EmployeesWrite: 'Employees.Write',
  PyramidView: 'Pyramid.View',
  FinanceOwn: 'Finance.Own',
  FinanceAll: 'Finance.All',
  PartnersRead: 'Partners.Read',
  PartnersWrite: 'Partners.Write',
  ServicesRead: 'Services.Read',
  ServicesWrite: 'Services.Write',
  ContractsRead: 'Contracts.Read',
  ContractsWrite: 'Contracts.Write',
  OnboardingRead: 'Onboarding.Read',
  OnboardingWrite: 'Onboarding.Write',
  AgendaRead: 'Agenda.Read',
  AgendaWrite: 'Agenda.Write',
  AgendaOthers: 'Agenda.Others',
  SopsRead: 'Sops.Read',
  SopsWrite: 'Sops.Write',
  AppsRead: 'Apps.Read',
  AppsWrite: 'Apps.Write',
  TodosRead: 'Todos.Read',
  TodosWrite: 'Todos.Write',
  TodosAll: 'Todos.All',
  Settings: 'Settings',
  ShareLinks: 'ShareLinks',
  Profiles: 'Profiles',
  Categories: 'Categories',
  EmailsRead: 'Emails.Read',
  EmailsWrite: 'Emails.Write',
  EmailsSend: 'Emails.Send',
  FaqsRead: 'Faqs.Read',
  FaqsWrite: 'Faqs.Write',
} as const

export type Permission = (typeof Permissions)[keyof typeof Permissions]

export const ALL_PERMISSIONS = Object.values(Permissions)

export const PERMISSION_LABELS: Record<Permission, string> = {
  [Permissions.Dashboard]: 'Dashboard',
  [Permissions.ClientsRead]: 'Clientes — leitura',
  [Permissions.ClientsWrite]: 'Clientes — escrita',
  [Permissions.EmployeesRead]: 'Minha equipe — leitura',
  [Permissions.EmployeesWrite]: 'Minha equipe — escrita',
  [Permissions.PyramidView]: 'Pirâmide de comando',
  [Permissions.FinanceOwn]: 'Financeiro próprio',
  [Permissions.FinanceAll]: 'Financeiro geral',
  [Permissions.PartnersRead]: 'Parceiras — leitura',
  [Permissions.PartnersWrite]: 'Parceiras — escrita',
  [Permissions.ServicesRead]: 'Serviços — leitura',
  [Permissions.ServicesWrite]: 'Serviços — escrita',
  [Permissions.ContractsRead]: 'Contratos — leitura',
  [Permissions.ContractsWrite]: 'Contratos — escrita',
  [Permissions.OnboardingRead]: 'Onboarding — leitura',
  [Permissions.OnboardingWrite]: 'Onboarding — escrita',
  [Permissions.AgendaRead]: 'Agenda — leitura',
  [Permissions.AgendaWrite]: 'Agenda — escrita',
  [Permissions.AgendaOthers]: 'Agenda — reuniões alheias',
  [Permissions.SopsRead]: 'SOPs — leitura',
  [Permissions.SopsWrite]: 'SOPs — escrita',
  [Permissions.AppsRead]: 'Apps — leitura',
  [Permissions.AppsWrite]: 'Apps — escrita',
  [Permissions.TodosRead]: 'To do — leitura',
  [Permissions.TodosWrite]: 'To do — escrita',
  [Permissions.TodosAll]: 'To do — todos os usuários',
  [Permissions.Settings]: 'Configurações',
  [Permissions.ShareLinks]: 'Links de compartilhamento',
  [Permissions.Profiles]: 'Perfis',
  [Permissions.Categories]: 'Categorias',
  [Permissions.EmailsRead]: 'E-mails — leitura',
  [Permissions.EmailsWrite]: 'E-mails — escrever/contas',
  [Permissions.EmailsSend]: 'E-mails — envio programado',
  [Permissions.FaqsRead]: 'FAQs — leitura',
  [Permissions.FaqsWrite]: 'FAQs — gerenciar (admin)',
}
